# Generated by Django 6.0.1 on 2026-01-15 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Приоритет дня (чем выше значение, тем выше приоритет)')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('schedule_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расписание на день',
                'verbose_name_plural': 'Расписания на дни',
                'ordering': ['-date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=1)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
                'ordering': ['order', 'priority', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField()),
                ('minute', models.PositiveSmallIntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_start', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='planner.dailyschedule')),
            ],
            options={
                'ordering': ['hour', 'minute'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['user', 'date'], name='planner_dai_user_id_035139_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['user', '-date'], name='planner_dai_user_id_8e214f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyschedule',
            index=models.Index(fields=['date'], name='planner_dai_date_e580e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyschedule',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_schedule_per_user_per_day'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['schedule', 'is_occupied'], name='planner_tim_schedul_4f8080_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('schedule', 'hour', 'minute')},
        ),
    ]
