# Generated by Django 6.0.1 on 2026-01-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='timeslot',
            name='planner_tim_schedul_4f8080_idx',
        ),
        migrations.DeleteModel(
            name='TaskTemplate',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
